#!/bin/bash

REPORT_FILE="/tmp/user_audit_report_$(date +%F).txt"

echo "======================================" > "$REPORT_FILE"
echo "        Linux User Audit Report        " >> "$REPORT_FILE"
echo "======================================" >> "$REPORT_FILE"
echo "Generated on: $(date)" >> "$REPORT_FILE"
echo "Hostname: $(hostname)" >> "$REPORT_FILE"
echo "Generated by: $(whoami)" >> "$REPORT_FILE"
echo >> "$REPORT_FILE"

echo "===== USERS =====" >> "$REPORT_FILE"
cut -d: -f1 /etc/passwd >> "$REPORT_FILE"
echo >> "$REPORT_FILE"

echo "===== GROUPS =====" >> "$REPORT_FILE"
cut -d: -f1 /etc/group >> "$REPORT_FILE"
echo >> "$REPORT_FILE"

echo "===== SUDO USERS =====" >> "$REPORT_FILE"

echo "Users in wheel group:" >> "$REPORT_FILE"
getent group wheel >> "$REPORT_FILE"

echo >> "$REPORT_FILE"
echo "Users in sudo group:" >> "$REPORT_FILE"
getent group sudo >> "$REPORT_FILE"

echo >> "$REPORT_FILE"
echo "Sudoers file entries:" >> "$REPORT_FILE"
grep -v '^#' /etc/sudoers 2>/dev/null | grep -v '^$' >> "$REPORT_FILE"

echo >> "$REPORT_FILE"
echo "Sudoers.d entries:" >> "$REPORT_FILE"
ls -l /etc/sudoers.d/ 2>/dev/null >> "$REPORT_FILE"

echo >> "$REPORT_FILE"

echo "===== LAST LOGIN DETAILS =====" >> "$REPORT_FILE"
lastlog >> "$REPORT_FILE"
echo >> "$REPORT_FILE"

echo "===== RECENT LOGIN HISTORY =====" >> "$REPORT_FILE"
last -n 10 >> "$REPORT_FILE"
echo >> "$REPORT_FILE"

echo "===== PASSWORD EXPIRY DETAILS =====" >> "$REPORT_FILE"

while IFS=: read -r username password uid gid comment home shell
do
    if [ "$uid" -ge 1000 ] && [ "$shell" != "/sbin/nologin" ] && [ "$shell" != "/bin/false" ]; then
        echo "User: $username" >> "$REPORT_FILE"
        sudo chage -l "$username" >> "$REPORT_FILE" 2>/dev/null
        echo "--------------------------------------" >> "$REPORT_FILE"
    fi
done < /etc/passwd

echo >> "$REPORT_FILE"
echo "===== ACCOUNT LOCK STATUS =====" >> "$REPORT_FILE"

while IFS=: read -r username password uid gid comment home shell
do
    if [ "$uid" -ge 1000 ] && [ "$shell" != "/sbin/nologin" ] && [ "$shell" != "/bin/false" ]; then
        echo "User: $username" >> "$REPORT_FILE"
        sudo passwd -S "$username" >> "$REPORT_FILE" 2>/dev/null
        echo "--------------------------------------" >> "$REPORT_FILE"
    fi
done < /etc/passwd

echo >> "$REPORT_FILE"
echo "Report saved at: $REPORT_FILE"

echo "User audit completed."
echo "Report saved at: $REPORT_FILE"
